#!/bin/sh

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $GOIDDD_USERNAME WITH PASSWORD '$GOIDDD_PASSWORD';

    CREATE DATABASE $GOIDDD_LOCAL_DATABASE;
    GRANT ALL privileges ON DATABASE $GOIDDD_LOCAL_DATABASE to $GOIDDD_USERNAME;

    CREATE DATABASE $GOIDDD_TEST_DATABASE;
    GRAND ALL privileges ON DATABASE $GOIDDD_TEST_DATABASE8 to $GOIDDD_USERNAME
EOSQL